{% set name = "python-gmatelastoplasticfinitestrainsimo" %}
{% set version = "0.2.2" %}
{% set sha256 = "abf2277f28d4ed191e044ddfce1cecf3eff9dc55776afafe180cc361adefa931" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<39 and osx and not x86_64]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pip
    - pyxtensor
    - gmattensor
  run:
    - python

test:
  imports:
    - GMatElastoPlasticFiniteStrainSimo

about:
  home: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Finite strain elasto-plastic model (Python wrapper).
  description: Finite strain elasto-plastic model (Python wrapper).
  doc_url: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo
  dev_url: https://github.com/tdegeus/GMatElastoPlasticFiniteStrainSimo

extra:
  recipe-maintainers:
    - tdegeus
